server:
  port: 8080

spring:
  application:
    name: keycloak-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

jwt:
  auth:
    converter:
      resource-id: ${RESOURCE_ID}
      principal-attribute: preferred_username